version: 2

models:
  - name: stg_green_tripdata
    description: Raw standardized green taxi data.

    columns:
      - name: lpep_pickup_datetime
        description: Pickup timestamp

      - name: lpep_dropoff_datetime
        description: Dropoff timestamp

      - name: payment_type
        description: Raw payment type code

  - name: stg_yellow_tripdata
    description: Raw standardized yellow taxi data.

    columns:
      - name: tpep_pickup_datetime
        description: Pickup timestamp

      - name: tpep_dropoff_datetime
        description: Dropoff timestamp

      - name: payment_type
        description: Raw payment type code



# version: 2

# models:
#   - name: stg_green_tripdata
#     description: Staging model for green taxi trip data.

#   - name: stg_yellow_tripdata
#     description: Staging model for yellow taxi trip data.

#   - name: int_trips_unioned
#     description: Intermediate model combining yellow and green taxi trips.