version: 2

models:
  - name: dim_zones
    description: >
      Dimension table for NYC taxi zones.
      One row per location_id.

    columns:
      - name: location_id
        description: Primary key for taxi zones.
        tests:
          - unique
          - not_null

      - name: borough
        description: NYC borough name.

      - name: zone
        description: Taxi zone / neighborhood name.

      - name: service_zone
        description: Service zone type.

  - name: fct_trips
    description: >
      Fact table containing all taxi trips from green and yellow taxis.
      One row per trip.

    columns:
      - name: trip_id
        description: Unique hashed identifier for each taxi trip.
        tests:
          - unique
          - not_null

      - name: service_type
        description: Taxi service type (Green or Yellow).
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["Green", "Yellow"]

      - name: vendorid
        description: Taxi vendor identifier.
        tests:
          - not_null

      - name: pickup_datetime
        description: Timestamp when trip started.
        tests:
          - not_null

      - name: dropoff_datetime
        description: Timestamp when trip ended.
        tests:
          - not_null

      - name: pickup_locationid
        description: Pickup taxi zone ID.
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_zones')
                field: location_id

      - name: dropoff_locationid
        description: Dropoff taxi zone ID.
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_zones')
                field: location_id

      - name: fare_amount
        description: Base fare amount.

      - name: total_amount
        description: Total fare charged.
        tests:
          - not_null

      - name: payment_type_description
        description: Human-readable payment type description.

# version: 1

# models:
#   - name: dim_zones
#     description: >
#       Dimension table for NYC taxi zones.
#       Contains borough and zone name information.

#     columns:
#       - name: location_id
#         description: Unique identifier for taxi zone.
#         tests:
#           - unique
#           - not_null

#       - name: borough
#         description: NYC borough name.

#       - name: zone
#         description: Taxi zone / neighborhood name.

#       - name: service_zone
#         description: Service zone category (Yellow, Green, Airport).

#   - name: fct_trips
#     description: |
#       Fact table containing all taxi trips from yellow and green taxis.
#       Each row represents one trip.

#     columns:
#       - name: trip_id
#         description: Unique hashed identifier for each taxi trip.

#       - name: vendorid
#         description: Taxi vendor identifier.

#       - name: pickup_datetime
#         description: Timestamp when trip started.

#       - name: dropoff_datetime
#         description: Timestamp when trip ended.

#       - name: total_amount
#         description: Total fare charged for the trip.